### ISSUE TITLE
Cant to see obj in CLI 

### ISSUE THREAD

**Issue by yanis7774** [diegodorado/blend2decentraland#1]
Hi. 
Thanks for addon. 

Can you see an obj files in CLI, CLI isnt supported obj yet?

**Comment by diegodorado** [comment]
I still cannot manage to make CLI work, nor in windows neither in linux

**Comment by yanis7774** [comment]
Did you get it now? Is a-obj rendering?

**Comment by diegodorado** [comment]
Oh, i havent tried since the recent update. It should probably work? Although there was still some issue with some materials
